repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      name: Ensure black code formatting
      language_version: python3.9
      args: ["--line-length=79", "--diff"]
      verbose: true
      exclude: |
          (?x)(
              __init__.py
          )
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      name: Ensure flake8 compliance
      args: ['--ignore=W605,C901,F841,W503']
      language_version: python3.9
      verbose: true
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: Ensure python modules are sorted
      language_version: python3.9
      verbose: true
      files: \.(py)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
      name: Ensure files end in a newline
      language_version: python3.9
      verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
      name: Ensure trailing whitespace is removed
      language_version: python3.9
      args: ["--markdown-linebreak-ext=md"]
      verbose: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
    - id: bandit
      name: Ensure compliance with security checks
      language_version: python3.9
      args: ["--quiet", "--recursive", "--skip=B101,B110,B311,B404,B603,B608"]
      verbose: true
      files: \.(py)$
      exclude: |
          (?x)(
              __init__.py
          )
