name: text-clustering
channels:
  - conda-forge
dependencies:
  - python
  - pip==22.1.2
  - pip:
    - jupyter==1.0.0
    - jupyterlab==3.4.3
    - papermill==2.3.4
    - nb-black==1.0.7
    - numpy==1.23.1
    - pandas==1.4.3
    - scikit-learn==1.1.1
    - gensim==4.2.0
    - nltk==3.7
    - jsonpickle==2.0.0
    - matplotlib==3.5.2
    - seaborn==0.11.2
    - lxml==4.9.1
    - python-dotenv==0.20.0
    - pymysql==1.0.2
    - pyarrow==8.0.0
    - fastparquet==0.8.1
    - prefect>=2.0b
